version: '3'

vars:
  BINARY_NAME: patina
  REPO: github.com/scottbrown
  PKG: "{{.REPO}}/{{.BINARY_NAME}}"
  pwd:
    sh: pwd
  BUILD_DIR: "{{.pwd}}/.build"
  TEST_DIR: "{{.pwd}}/.test"

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} {{.PKG}}/cmd/{{.BINARY_NAME}}
    sources:
      - "**/*.go"
    generates:
      - "{{.BINARY_NAME}}"

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile={{.TEST_DIR}/coverage.out ./...
      - go tool cover -func={{.TEST_DIR}/coverage.out

  test:coverage:html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile={{.TEST_DIR}/coverage.out ./...
      - go tool cover -html={{.TEST_DIR}/coverage.out -o {{.TEST_DIR}/coverage.html

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BUILD_DIR}} {{.TEST_DIR}}

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  all:
    desc: Run fmt, lint, test, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build
