version: '3'

vars:
  BINARY_NAME: patina
  BUILD_DIR: ./cmd/patina

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build the binary
    cmds:
      - go build -o {{.BINARY_NAME}} {{.BUILD_DIR}}
    sources:
      - "**/*.go"
    generates:
      - "{{.BINARY_NAME}}"

  test:
    desc: Run all tests
    cmds:
      - go test -v ./...

  test:coverage:
    desc: Run tests with coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -func=coverage.out

  test:coverage:html:
    desc: Generate HTML coverage report
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -f {{.BINARY_NAME}}
      - rm -f coverage.out coverage.html

  install:
    desc: Install the binary to GOPATH/bin
    cmds:
      - go install {{.BUILD_DIR}}

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  all:
    desc: Run fmt, lint, test, and build
    cmds:
      - task: fmt
      - task: lint
      - task: test
      - task: build
